//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pacjent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacjent()
        {
            this.Rejestracja = new HashSet<Rejestracja>();
        }
    
        public int IdPacjenta { get; set; }
        [Required]
        public string Imie { get; set; }
        [Required]
        public string Nazwisko { get; set; }
        [Required]
        public string Adres { get; set; }
        [Required]
        public string Pesel { get; set; }
        [Required]
        public string NumerTelefonu { get; set; }
        public bool Zatwierdzono { get; set; }
        [Required]
        public string Miasto { get; set; }
        [Required]
        public string KodPocztowy { get; set; }
        public Nullable<int> IdUzytkownika { get; set; }

        [Required]
        public virtual Uzytkownik Uzytkownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rejestracja> Rejestracja { get; set; }
    }
}
