//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolaUzytkownika
    {
        public int IdRoliUzytkownika { get; set; }
        public int IdRoli { get; set; }
        public int IdUzytkownika { get; set; }
    
        public virtual Rola Rola { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
