//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SpecjalizacjaLekarza
    {
        public int IdSpecjalizacjiLekarza { get; set; }
        [Required]
        public int IdSpecjalizacji { get; set; }
        [Required]
        public int IdLekarza { get; set; }

        [Required]
        public virtual Lekarz Lekarz { get; set; }
        public virtual Specjalizacja Specjalizacja { get; set; }
    }
}
