//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrzychodniaBDEntities7 : DbContext
    {
        public PrzychodniaBDEntities7()
            : base("name=PrzychodniaBDEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Lekarz> Lekarz { get; set; }
        public virtual DbSet<Pacjent> Pacjent { get; set; }
        public virtual DbSet<Recepcjonista> Recepcjonista { get; set; }
        public virtual DbSet<Rola> Rola { get; set; }
        public virtual DbSet<RolaUzytkownika> RolaUzytkownika { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
        public virtual DbSet<DzienGodzinaPracyLekarza> DzienGodzinaPracyLekarza { get; set; }
        public virtual DbSet<Rejestracja> Rejestracja { get; set; }
        public virtual DbSet<Specjalizacja> Specjalizacja { get; set; }
        public virtual DbSet<SpecjalizacjaLekarza> SpecjalizacjaLekarza { get; set; }
        public virtual DbSet<Wizyta> Wizyta { get; set; }
    }
}
