//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejestracja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rejestracja()
        {
            this.Wizyta = new HashSet<Wizyta>();
        }
    
        public int IdRejestracji { get; set; }
        public System.DateTime DataRozp { get; set; }
        public System.DateTime DataZak { get; set; }
        public string CzyZajeta { get; set; }
        public int IdLekarza { get; set; }
        public Nullable<int> IdPacjenta { get; set; }
    
        public virtual Lekarz Lekarz { get; set; }
        public virtual Pacjent Pacjent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wizyta> Wizyta { get; set; }
    }
}
