//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Specjalizacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specjalizacja()
        {
            this.SpecjalizacjaLekarza = new HashSet<SpecjalizacjaLekarza>();
        }
    
        public int IdSpecjalizacji { get; set; }
        public string NazwaSpecjalizacji { get; set; }
        public IEnumerable<SelectListItem> ListaSpecjalizacji { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecjalizacjaLekarza> SpecjalizacjaLekarza { get; set; }
    }
}
