//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaMvc.Models.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int IdWizyty { get; set; }
        public string Koszt { get; set; }
        public int IdRejestracji { get; set; }
    
        public virtual Rejestracja Rejestracja { get; set; }
    }
}
